apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./fe

images:
 - name: nginx
   newName: '10.100.1.140/dev-myproject/mynginx'
   newTag: '1.16'
patches:
- target:
    kind: Deployment
    name: nginx
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 2
