apiVersion: v1
kind: Service
metadata:
  name: svc-nginx-fe
spec:
    type: ClusterIP
    ports:
      - name: http
        protocol: TCP
        port: 8811
        targetPort: 80
    externalIPs:
      - 10.100.1.140
